const Dishdata = [
    {
        id:1,
        title:'CHOLE CHAWAL',
        image:'images/android-dev.png',
        price:'100',
        aboutDish:'All time favourite chole chawal.. Golden Pearl Like chola with steamed jeera rice garnished with onion and papad.',
        meal:'Lunch',
    },
    {
        id:2,
        title:'KADHI CHAWAL',
        image:'images/got.png',
        price:'80',
        aboutDish:'Tangy kadhi with steam jeera rice served with two pakodas garnished with onion and papad.',
        meal:'Lunch',
    },
    {
        id:3,
        title:'SHAHI PANEER',
        image:'images/sex_ed.jpg',
        price:'110',
        aboutDish:'Restaurant special smooth gravy with soft pieces of paneer cooked with tomato puri and cashew paste garnished with coriander and ginger.',
        meal:'Dinner',
    },
    {
        id:4,
        title:'MAKHANI DAAL',
        image:'images/lucifer.jpg',
        price:'90',
        aboutDish:'Buttery fried Daal with lots n lots of cream and butter ganrnished on top garnished with coriander and ginger.',
        meal:'Dinner',
    },
    {
        id:5,
        title:'JEERA RICE',
        image:'images/vikings.jpg',
        price:'50',
        aboutDish:'very healthy and light steam cooked rice garnished with coriander and peas.',
        meal:'Lunch',
    },
    {
        id:6,
        title:'BUTTER NAAN',
        image:'images/ragnarok.jpg',
        price:'30',
        aboutDish:'Indian taco with butter cooked in tandoor garnished with coriander and butter.',
        meal:'Dinner',
    },
    {
        id:7,
        title:'RAJMA CHAWAL',
        image:'images/app-dev.png',
        price:'100',
        aboutDish:'Tangy Rajma saute in ginger-garlic paste and a lots tomato n onion served hot with steam cooked Jeera Rice garnished with coriander',
        meal:'Lunch',
    },
    {
        id:8,
        title:'STUFFED LACCHA PARATHA',
        image:'images/got.png',
        price:'40',
        aboutDish:'40 layers paratha served with AMUL Butter, Dahi and Pickel.',
        meal:'Lunch',
    },
    {
        id:9,
        title:'STUFF NAAN',
        image:'images/got.png',
        price:'45',
        aboutDish:'Indian taco with butter cooked in tandoor stuffed with cottage cheese and dry fruits, garnished with coriander and butter.',
        meal:'Dinner',
    },
    {
        id:10,
        title:'GULAB JAAMUN',
        image:'images/got.png',
        price:'20',
        aboutDish:'Sweet n sexy 2 piece of Gulab Jamun served hot coated with sugar syrup coated.',
        meal:'Sweets',
    },
    {
        id:11,
        title:'RAS MALAI',
        image:'images/got.png',
        price:'20',
        aboutDish:'Cool n cute 1 piece of Ras Malai served with a lot of rabri and dry fruits.',
        meal:'Sweets',
    }
];

export default Dishdata;